def mainDir="Part2_Docker/Chapter02/2-jenkins-docker"
def ecrLoginHelper="docker-credential-ecr-login"
def region="koreacentral"
def ecrUrl="shjtestacr01.azurecr.io"
def repository="test"
def deployHost="10.2.0.4"
def azureAcrLoginCommand="az acr login -n <registry name> -u <service principal의 app id >  -p <service princial의 client pw>"


pipeline {
    agent any

    stages {
        stage('Pull Codes from Github'){
            steps{
                checkout scm
            }
        }
        stage('Build Codes by Gradle') {
            steps {
                sh """
                cd ${mainDir}
                ./gradlew clean build
                """
            }
        }
        stage('Build Docker Image by Jib & Push to AWS ECR Repository') {
            steps {
                    sh """
                        docker login shjtestacr01.azurecr.io -u shjtestacr01 --password-stdin < /home/shj/password.txt
                        cd ${mainDir}
                        ./gradlew jib -Djib.to.image=${ecrUrl}/${repository}:${currentBuild.number} -Djib.console='plain'
                    """
                
            }
        }
        stage('Deploy to Azure VM'){
            steps{
                    sh "ssh -i /home/shj/server-key.pem shj@10.2.0.4 \
                      docker run -d -p 80:8080 -t ${ecrUrl}/${repository}:${currentBuild.number};'"
            }
        }
    }
}
